// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetWeltrettung.Models;

#nullable disable

namespace ProjetWeltrettung.Migrations
{
    [DbContext(typeof(ProjetWeltrettungContext))]
    partial class ProjetWeltrettungContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetWeltrettung.Models.Aggressor", b =>
                {
                    b.Property<int>("AggressorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AggressorId"));

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spezialgebiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AggressorId");

                    b.ToTable("Aggressoren");
                });

            modelBuilder.Entity("ProjetWeltrettung.Models.Bedrohung", b =>
                {
                    b.Property<int>("BedrohungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedrohungId"));

                    b.Property<int>("AggressorId")
                        .HasColumnType("int");

                    b.Property<string>("Bedrohungsname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Existiert")
                        .HasColumnType("bit");

                    b.Property<int?>("HeldId")
                        .HasColumnType("int");

                    b.HasKey("BedrohungId");

                    b.HasIndex("AggressorId");

                    b.HasIndex("HeldId");

                    b.ToTable("Bedrohungen");
                });

            modelBuilder.Entity("ProjetWeltrettung.Models.Held", b =>
                {
                    b.Property<int>("HeldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeldId"));

                    b.Property<string>("Beruf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeldId");

                    b.ToTable("Helden");
                });

            modelBuilder.Entity("ProjetWeltrettung.Models.Weltretter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faehigkeit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IstVolljaehrig")
                        .HasColumnType("bit");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weltretter");
                });

            modelBuilder.Entity("ProjetWeltrettung.Models.Bedrohung", b =>
                {
                    b.HasOne("ProjetWeltrettung.Models.Aggressor", "Aggressor")
                        .WithMany("Bedrohungen")
                        .HasForeignKey("AggressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetWeltrettung.Models.Held", "Held")
                        .WithMany("Bedrohungen")
                        .HasForeignKey("HeldId");

                    b.Navigation("Aggressor");

                    b.Navigation("Held");
                });

            modelBuilder.Entity("ProjetWeltrettung.Models.Aggressor", b =>
                {
                    b.Navigation("Bedrohungen");
                });

            modelBuilder.Entity("ProjetWeltrettung.Models.Held", b =>
                {
                    b.Navigation("Bedrohungen");
                });
#pragma warning restore 612, 618
        }
    }
}
